version: "3"
networks:
    kafka_kafkanet:
        external: true

services:
    reddit:
        build: .
        hostname: reddit                                                      
        container_name: reddit
        volumes:
            - .:/app
        networks:                                                               
            - kafka_kafkanet
