version: "3"
networks:
    kafka_kafkanet:
        external: true

services:
    fb:
        build: .
        hostname: fb
        container_name: fb
        #environment:
        #    - DEVELOPMENT=true
        volumes:
            - .:/app
        networks:
            - kafka_kafkanet
