version: "3"
networks:
    kafka_kafkanet:
        external: true

services:
    twitter:
        build: .
        hostname: twitter                                                         
        container_name: twitter
        #environment:                                                            
        #    - DEVELOPMENT=true
        volumes:
            - .:/app
        networks:                                                                                                                          
            - kafka_kafkanet
